[App]
ImageWidth=3000
Felder=Box,Quantity,Device,Alias,Category,Comment,Package
Kategorie=Heizung, Wasser, Elektro, Maurer, Fliesen, Garten, Elektronikbauteile, El-Baugruppen, Haushalt, Werkzeug, Messen

[Box]
Titel=ChaosBox
ImageWidth=2048

[Box]
Titel=BilderBox
Felder=Box,,,Tags,Category,Comment
Kategorie=Familie, Berg, Urlaub

[Poster]
#in Pixel
POSTER-LIMIT=6000
#in mm
POSTER-SIZE=200x100
POSTER-COLS=3
POSTER-ROWS=3
POSTER-FIX=true
POSTER-MARGIN-LEFT=15
POSTER-MARGIN-RIGHT=10
POSTER-MARGIN-TOP=10
POSTER-MARGIN-BOTTOM=15
POSTER-FRAMES=eeee
POSTER-BACKGROUND-COLOR=9bb195
POSTER-IMAGE-BACKGROUND-COLOR=FFFFFF
POSTER-IMAGE-PADDING=2

[TextSnippets]
chatgpt="Analysiere die technischen Bauteile auf dem Bild. Fasse gleiche Bauteile zusammen und gib pro Bauteiltyp genau eine Zeile aus:
Anzahl | Bauteil | Kategorie | Kurzbeschreibung
Vorgaben:
- Benenne das Bauteil möglichst genau anhand sichtbarer Merkmale und Beschriftungen.
- Wähle eine Kategorie
- Zähle nur sichtbare, eindeutig unterscheidbare Stücke. Bei Unsicherheit schreibe  "?"
- Beschreibe Bauform, lesbare Kennzeichnung und erkennbare Eigenschaften in höchstens 12 Wörtern.
- Erfinde keine Typnummern, technischen Werte oder Funktionen. Kennzeichne unsichere Zuordnungen mit „???“.
- Gib ausschließlich die Ergebniszeilen aus, ohne Einleitung
"

gemini="Analysiere das Bild mit den technischen Bauteilen. Erstelle eine knappe Übersicht als Tabelle mit folgenden Spalten:
1. Stückzahl: Anzahl im Bild
2. Bauteil: Name/Bezeichnung des Bauteils (kurz & präzise)
3. Kategorie: Zuordnung (z. B. Schrauben/Fastener, Elektronik, Pneumatik, Dichtung, Mechanik)
4. Technische Details
Zusatzregeln:
- Antworte ausschließlich in Stichpunkten / Tabellenform ohne Fließtext.
- Unbekannte Teile mit ??? kennzeichnen."




[SSH]
Host=access983197478.webspace-data.io
Port=22
User=u114229695
ImageDestination=l1/storage/app/exif/jpg
DataDestination=l1/storage/app/exif/data
KeyFile=/home/roland/Dokumente/ChatGPT/chaosbox-desktop/BilderBox/.state/credentials/id_ed25519
KnownHosts=/home/roland/Dokumente/ChatGPT/chaosbox-desktop/BilderBox/.state/credentials/known_hosts
