
[App]
Standard=Chaosbox

[App.Chaosbox]
Titel=Chaosbox
JPG=ChaosBox/JPG
Daten=ChaosBox/boxes
Felder=Box,Quantity,Device,Alias,Category,Comment,Package
Kategorie=Heizung, Wasser, Elektro, Maurer, Fliesen, Garten, Elektronikbauteile, El-Baugruppen, Haushalt, Werkzeug, Messen

[App.Bilderbox]
Titel=Bilderbox
JPG=Bilderbox/JPG
Daten=Bilderbox/boxes
Felder=Box,,,Tags,Category,Comment
Kategorie=Familie, Berg, Urlaub

[ImageSize]
LIMIT=3000

[Poster]
POSTER-LIMIT=6000
POSTER-SIZE=200x100
POSTER-COLS=3
POSTER-ROWS=3
POSTER-FIX=true
POSTER-MARGIN-LEFT=15
POSTER-MARGIN-RIGHT=10
POSTER-MARGIN-TOP=10
POSTER-MARGIN-BOTTOM=15
POSTER-FRAMES=eeee
POSTER-BACKGROUND-COLOR=9bb195
POSTER-IMAGE-BACKGROUND-COLOR=FFFFFF
POSTER-IMAGE-PADDING=2

[TextSnippets]
chatgpt="Analysiere die technischen Bauteile auf dem Bild. Fasse gleiche Bauteile zusammen und gib pro Bauteiltyp genau eine Zeile aus:
Anzahl | Bauteil | Kategorie | Kurzbeschreibung
Vorgaben:
- Benenne das Bauteil möglichst genau anhand sichtbarer Merkmale und Beschriftungen.
- Wähle eine Kategorie
- Zähle nur sichtbare, eindeutig unterscheidbare Stücke. Bei Unsicherheit schreibe  "?"
- Beschreibe Bauform, lesbare Kennzeichnung und erkennbare Eigenschaften in höchstens 12 Wörtern.
- Erfinde keine Typnummern, technischen Werte oder Funktionen. Kennzeichne unsichere Zuordnungen mit „???“.
- Gib ausschließlich die Ergebniszeilen aus, ohne Einleitung
"

gemini="Analysiere das Bild mit den technischen Bauteilen. Erstelle eine knappe Übersicht als Tabelle mit folgenden Spalten:
1. Stückzahl: Anzahl im Bild
2. Bauteil: Name/Bezeichnung des Bauteils (kurz & präzise)
3. Kategorie: Zuordnung (z. B. Schrauben/Fastener, Elektronik, Pneumatik, Dichtung, Mechanik)
4. Technische Details
Zusatzregeln:
- Antworte ausschließlich in Stichpunkten / Tabellenform ohne Fließtext.
- Unbekannte Teile mit ??? kennzeichnen."



